[package]
name = "rts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependenciess]
sdl2 = "0.36.0"

[dependencies]
rand = "0.8.5"

[dependencies.sdl2]
default-features = false
features = ["bundled", "image"]
